# Generated by Django 4.2.1 on 2023-05-25 15:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("HackSubmit", "0002_alter_hackathon_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hackathon",
            name="type",
            field=models.CharField(
                choices=[("image", "Image"), ("file", "File"), ("link", "Link")],
                default="image",
                max_length=10,
            ),
        ),
    ]
