# Generated by Django 4.2.1 on 2023-05-25 15:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("HackSubmit", "0003_alter_hackathon_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="hackathon",
            name="participants",
            field=models.ManyToManyField(
                related_name="participants", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="submission",
            name="file",
            field=models.FileField(
                blank=True, null=True, upload_to="submissions/files/"
            ),
        ),
        migrations.AddField(
            model_name="submission",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="submissions/images/"
            ),
        ),
        migrations.AddField(
            model_name="submission",
            name="link",
            field=models.URLField(blank=True, null=True),
        ),
    ]
